# Package Overview
package_name: heart_model

# Data Files
training_data_file: heart_attack_dataset.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: Heart_Attack_Risk

pipeline_name: heart_model
pipeline_save_file: heart__model_output_v

features:      # final features to be use
  - Age
  - Sex
  - Cholesterol
  
  - Heart_Rate
  - Diabetes
  - Alcohol_Consumption
  - Diet

  - BP_Systolic
  


unused_fields:  # Features to drop before pipeline
  - Patient_ID


# Features inside processing pipeline
  
diet_var: Diet

gender_var: Sex

age_var: Age


gender_mappings:
  Female: 0
  Male: 1

diet_mappings:
  Unhealthy: 0
  Average: 1
  Healthy: 2

  
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 5

